channels:
  - bioconda
  - r
  - mdekstrand
  - conda-forge
dependencies:
  - numpy
  - scipy
  - pysam>=0.8.4
  - hdf5>=1.8
  - pytables=3
  - gatk4=4.0.4
  - snpsift
  - star
  - ncurses
  - samtools
  - bwa
  - tabix
  - bcftools
  - r-plyr
  - r-rmutil
  - bioconductor-rtracklayer
  - r-dplyr